import type { PathConfig } from '@/types/puzzle';
import { PATH_IDS } from '@/lib/paths';

/**
 * Pop Culture Path - Friends & Gilmore Girls Themed Puzzles
 * Path ID: 1 (Central Perk Purple & Stars Hollow Yellow)
 */
export const popCulturePath: PathConfig = {
  pathId: PATH_IDS.POP_CULTURE,
  name: 'Pop Culture',
  puzzles: [
    // --- FRIENDS (18 Questions Total) ---
    // Multiple Choice (9)
    {
      id: 'pop-6',
      type: 'multiple-choice',
      difficulty: 'easy',
      metadata: { show: 'friends' },
      question: "What is Joey's signature catchphrase?",
      options: ["How's it going?", "How you doin'?", "What's up?", "Hey, what's new?"],
      correctAnswer: 1,
      successMessage: "You nailed it! How YOU doin'? 😉",
      points: 10,
    },
    {
      id: 'pop-7',
      type: 'multiple-choice',
      difficulty: 'easy',
      metadata: { show: 'friends' },
      question: "Which character famously screams 'PIVOT!' while moving a couch?",
      options: ['Joey', 'Chandler', 'Ross', 'Monica'],
      correctAnswer: 2,
      successMessage: "PIVOT! PIVOT! PIVOOOT! 🛋️",
      points: 10,
    },
    {
      id: 'pop-8',
      type: 'multiple-choice',
      difficulty: 'easy',
      metadata: { show: 'friends' },
      question: "What is the name of the coffee shop where the gang hangs out?",
      options: ['Daily Grind', 'Central Perk', 'The Beanery', 'Coffee Garden'],
      correctAnswer: 1,
      successMessage: "Meet you on the orange couch! ☕",
      points: 10,
    },
    {
      id: 'pop-9',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      question: "What is Chandler Bing's middle name?",
      options: ['Michael', 'Milton', 'Muriel', 'Maurice'],
      correctAnswer: 2,
      successMessage: "Yes, Chandler Muriel Bing! 👔",
      points: 20,
    },
    {
      id: 'pop-10',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      question: "How many times was Ross Geller legally married?",
      options: ['2', '3', '4', '5'],
      correctAnswer: 1,
      successMessage: "Three divorces! He's the Divorce-O! 💍",
      points: 20,
    },
    {
      id: 'pop-11',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      question: "What is the name of Phoebe's most famous original song?",
      options: ['Sticky Shoes', 'Smelly Cat', 'Giant Pigeons', 'Paper Mache'],
      correctAnswer: 1,
      successMessage: "It's not your fault, Smelly Cat! 🐈",
      points: 20,
    },
    {
      id: 'pop-12',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      question: "Which character owns the stuffed penguin named 'Hugsy'?",
      options: ['Rachel', 'Emma', 'Joey', 'Phoebe'],
      correctAnswer: 2,
      successMessage: "Joey's bedtime penguin pal! 🐧",
      points: 20,
    },
    {
      id: 'pop-13',
      type: 'multiple-choice',
      difficulty: 'hard',
      metadata: { show: 'friends' },
      question: "What was the name of the character played by guest star Bruce Willis?",
      options: ['Paul Stevens', 'Peter Stevens', 'Phil Stevens', 'Patrick Stevens'],
      correctAnswer: 0,
      successMessage: "He's just a 'neat guy'! 💪",
      points: 30,
    },
    {
      id: 'pop-14',
      type: 'multiple-choice',
      difficulty: 'hard',
      metadata: { show: 'friends' },
      question: "In the final episode, where is Rachel supposed to move for her new job?",
      options: ['London', 'Paris', 'Rome', 'Milan'],
      correctAnswer: 1,
      successMessage: "She got off the plane! ✈️",
      points: 30,
    },
    // Text Input (4)
    {
      id: 'pop-15',
      type: 'text-input',
      difficulty: 'easy',
      metadata: { show: 'friends' },
      question: "What is Joey's favorite food?",
      correctAnswer: "Sandwiches",
      acceptableAnswers: ["sandwiches", "sandwich", "pizza"],
      placeholder: "Joey doesn't share...",
      successMessage: "Correct! Joey doesn't share food! 🥪",
      points: 10,
    },
    {
      id: 'pop-16',
      type: 'text-input',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      question: "What persona did Ross adopt to teach Ben about Hanukkah?",
      correctAnswer: "Holiday Armadillo",
      acceptableAnswers: ["the holiday armadillo", "holiday armadillo"],
      successMessage: "The Holiday Armadillo is here! 🐢",
      points: 20,
    },
    {
      id: 'pop-17',
      type: 'text-input',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      question: "What is the name of the guy who runs Central Perk?",
      correctAnswer: "Gunther",
      successMessage: "Gunther Central Perk! ☀️",
      points: 20,
    },
    {
      id: 'pop-18',
      type: 'text-input',
      difficulty: 'hard',
      metadata: { show: 'friends' },
      question: "What is Phoebe's birth mother's name?",
      correctAnswer: "Phoebe",
      acceptableAnswers: ["phoebe abbott"],
      successMessage: "Yes, Phoebe Sr.! Like mother, like daughter. 🐚",
      points: 30,
    },
    // Image Reveal (5)
    {
      id: 'pop-19',
      type: 'image-reveal',
      difficulty: 'easy',
      metadata: { show: 'friends' },
      imageUrl: '/puzzles/pop-culture/yellow-frame.png',
      imageAlt: 'A yellow picture frame on a purple door',
      question: "Whose apartment door features this iconic yellow frame?",
      correctAnswer: "Monica",
      successMessage: "You know your decor! 🖼️",
      points: 15,
    },
    {
      id: 'pop-20',
      type: 'image-reveal',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      imageUrl: '/puzzles/pop-culture/geller-cup.jpg',
      imageAlt: 'A troll doll nailed to a piece of wood',
      question: "What is the name of this prestigious family sports trophy?",
      correctAnswer: "Geller Cup",
      successMessage: "The Geller Cup! Monica hid it for years. 🏆",
      points: 25,
    },
    {
      id: 'pop-21',
      type: 'image-reveal',
      difficulty: 'hard',
      metadata: { show: 'friends' },
      imageUrl: '/puzzles/pop-culture/gladys.jpg',
      imageAlt: 'A creepy 3D piece of art with a woman coming out of a frame',
      question: "What is the name of this 'original' piece of art created by Phoebe?",
      correctAnswer: "Gladys",
      successMessage: "Gladys! Monica was terrified of her. 🎨",
      points: 35,
    },
    {
      id: 'pop-22',
      type: 'image-reveal',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      imageUrl: '/puzzles/pop-culture/white-dog.jpg',
      imageAlt: 'A large white ceramic dog statue',
      question: "Joey bought this for his apartment. What is the dog's name?",
      correctAnswer: "Pat",
      acceptableAnswers: ["pat the dog"],
      successMessage: "Pat the Dog! A classic Joey purchase. 🐕",
      points: 25,
    },
    {
      id: 'pop-23',
      type: 'image-reveal',
      difficulty: 'medium',
      metadata: { show: 'friends' },
      imageUrl: '/puzzles/pop-culture/magna-doodle.jpg',
      imageAlt: 'A magnetic drawing board on a door',
      question: "This drawing board is found in whose apartment?",
      correctAnswer: "Joey",
      acceptableAnswers: ["joey and chandler", "joey's"],
      successMessage: "The Magna Doodle! It always had a new drawing. ✍️",
      points: 25,
    },

    // --- GILMORE GIRLS (12 Questions Total) ---
    // Multiple Choice (6)
    {
      id: 'pop-24',
      type: 'multiple-choice',
      difficulty: 'easy',
      metadata: { show: 'gilmore' },
      question: "Who was Rory's very first boyfriend?",
      options: ['Jess', 'Logan', 'Dean', 'Tristan'],
      correctAnswer: 2,
      successMessage: "Classic Dean Forester! 🚲",
      points: 10,
    },
    {
      id: 'pop-25',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'gilmore' },
      question: "Which Ivy League school did Rory graduate from?",
      options: ['Harvard', 'Princeton', 'Yale', 'Columbia'],
      correctAnswer: 2,
      successMessage: "Bulldogs, Bulldogs, bow wow wow! 🎓",
      points: 20,
    },
    {
      id: 'pop-26',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'gilmore' },
      question: "What is the name of Lorelai's dog?",
      options: ['Paul Anka', 'Frank Sinatra', 'Dean Martin', 'Tony Bennett'],
      correctAnswer: 0,
      successMessage: "The dog who is afraid of peas! 🐕",
      points: 20,
    },
    {
      id: 'pop-27',
      type: 'multiple-choice',
      difficulty: 'hard',
      metadata: { show: 'gilmore' },
      question: "How many siblings does Lane Kim have?",
      options: ['0', '1', '2', '3'],
      correctAnswer: 0,
      successMessage: "Correct! She is an only child. 🥁",
      points: 30,
    },
    {
      id: 'pop-28', // RESERVED SLOT: MC HARD
      type: 'multiple-choice',
      difficulty: 'hard',
      metadata: { show: 'gilmore' },
      question: "Which of these was NOT one of Lorelai's boyfriends?",
      options: ['Jason', 'Max', 'Christopher', 'Digger'],
      correctAnswer: 3,
      successMessage: "Tricky! Digger was actually Jason's nickname. 🕵️‍♂️",
      points: 35,
    },
    {
      id: 'pop-29',
      type: 'multiple-choice',
      difficulty: 'medium',
      metadata: { show: 'gilmore' },
      question: "What is Sookie St. James's profession?",
      options: ['Innkeeper', 'Chef', 'Teacher', 'Doctor'],
      correctAnswer: 1,
      successMessage: "A master of the kitchen! 🥘",
      points: 20,
    },
    // Text Input (4)
    {
      id: 'pop-30',
      type: 'text-input',
      difficulty: 'easy',
      metadata: { show: 'gilmore' },
      question: "What is the name of the diner where Lorelai and Rory get their coffee?",
      correctAnswer: "Luke's",
      acceptableAnswers: ["lukes", "lukes diner", "luke's diner"],
      successMessage: "Coffee, coffee, coffee! ☕",
      points: 10,
    },
    {
      id: 'pop-31',
      type: 'text-input',
      difficulty: 'medium',
      metadata: { show: 'gilmore' },
      question: "Who is the resident of Stars Hollow who has held over 60 different jobs?",
      correctAnswer: "Kirk",
      acceptableAnswers: ["kirk gleason"],
      successMessage: "Classic Kirk! He does it all. 🏃‍♂️",
      points: 20,
    },
    {
      id: 'pop-32', // RESERVED SLOT: TEXT HARD
      type: 'text-input',
      difficulty: 'hard',
      metadata: { show: 'gilmore' },
      question: "What is the name of the rock band Lane plays drums for?",
      correctAnswer: "Hep Alien",
      successMessage: "Hep Alien! Ready to rock! 🎸",
      points: 35,
    },
    {
      id: 'pop-33', // RESERVED SLOT: TEXT MEDIUM/HARD
      type: 'text-input',
      difficulty: 'hard',
      metadata: { show: 'gilmore' },
      question: "What is the name of the annual festival with the hay bale maze?",
      correctAnswer: "Spring Fling",
      successMessage: "The Spring Fling Festival! 🌾",
      points: 30,
    },
    // Image Reveal (2)
    {
      id: 'pop-34',
      type: 'image-reveal',
      difficulty: 'easy',
      metadata: { show: 'gilmore' },
      imageUrl: '/puzzles/pop-culture/gazebo.jpg',
      imageAlt: 'A white gazebo in the center of a park',
      question: "What is this iconic Stars Hollow structure called?",
      correctAnswer: "Gazebo",
      successMessage: "The Stars Hollow Gazebo! 🏛️",
      points: 15,
    },
    {
      id: 'pop-35', // RESERVED SLOT: IMAGE HARD
      type: 'image-reveal',
      difficulty: 'hard',
      metadata: { show: 'gilmore' },
      imageUrl: '/puzzles/pop-culture/vulture.jpg',
      imageAlt: 'A picture of a vulture',
      question: "What animal did Rory compare her graduation hat to?",
      correctAnswer: "Vulture",
      successMessage: "A giant bird of prey! 🎓",
      points: 35,
    }
  ],
};
